-- Migration: Create study_plans table
-- Description: Stores personalized study plans generated by Trigger.dev tasks

CREATE TABLE IF NOT EXISTS study_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id UUID NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  overview TEXT,
  weak_topics JSONB DEFAULT '[]'::jsonb,
  priority_order JSONB DEFAULT '[]'::jsonb,
  plan_content JSONB NOT NULL DEFAULT '[]'::jsonb,
  progress_percent INTEGER NOT NULL DEFAULT 0 CHECK (progress_percent >= 0 AND progress_percent <= 100),
  target_date DATE,
  daily_minutes INTEGER NOT NULL DEFAULT 60 CHECK (daily_minutes > 0),
  model_used TEXT,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_study_plans_user_course_status 
  ON study_plans(user_id, course_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_study_plans_course 
  ON study_plans(course_id);
CREATE INDEX IF NOT EXISTS idx_study_plans_status 
  ON study_plans(status, created_at DESC);

-- RLS Policies
ALTER TABLE study_plans ENABLE ROW LEVEL SECURITY;

-- Users can view their own study plans
CREATE POLICY "Users can view their own study plans"
  ON study_plans FOR SELECT
  USING (auth.uid() = user_id);

-- System can insert study plans (via service role)
CREATE POLICY "System can insert study plans"
  ON study_plans FOR INSERT
  WITH CHECK (true);

-- Users can update their own study plans
CREATE POLICY "Users can update their own study plans"
  ON study_plans FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_study_plans_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER study_plans_updated_at
  BEFORE UPDATE ON study_plans
  FOR EACH ROW
  EXECUTE FUNCTION update_study_plans_updated_at();

